.TH ADLER32 1 "Last change: May 9th, 2021"
.SH NAME
adler32 \- calculate the Adler-32 checksum
.SH SYNOPSIS
.B adler32
[\fB\-q\fR]
.IR [files\ ...]
.SH DESCRIPTION
.B adler32
calculates the Adler-32 checksum of one or multiple files.
.SH OPTIONS
.TP
.BR \-q
Quiet mode - only the checksum is printed out.
.SH AUTHOR
Hannes Braun <hannesbraun@mail.de>